version: "3.8"
services:
    backend:
        build: ./backend
        container_name: node-backend
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - REDIS_URL=redis://redis:6379
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - redis

    frontend:
        build: ./frontend
        container_name: react-frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        command: npm run dev -- --host
        depends_on:
            - backend


    redis:
        image: redis:latest
        container_name: redis-server
        ports:
            - "6379:6379"
